# Generated by Django 2.1.3 on 2018-12-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('acdemic_unit', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('field', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('cited_times', models.IntegerField()),
                ('issn', models.CharField(db_column='ISSN', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'paper',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('paperid', models.ForeignKey(db_column='paperid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='homepage.Paper')),
                ('author_type', models.CharField(max_length=1000)),
                ('authorid', models.ForeignKey(db_column='authorid', on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.Author')),
            ],
            options={
                'db_table': 'paper_author',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterUniqueTogether(
            name='paperauthor',
            unique_together={('paperid', 'authorid')},
        ),
    ]
